from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor

prs = Presentation()
title_slide_layout = prs.slide_layouts[0]
bullet_slide_layout = prs.slide_layouts[1]

slide = prs.slides.add_slide(title_slide_layout)
title = slide.shapes.title
subtitle = slide.placeholders[1]
title.text = "Sistem Informasi Perumahan Bumi Trimulyo (SIP-BTR)"
subtitle.text = "Presentasi Proyek Akhir (UAS)\nIntegrasi Frontend & Backend Terpadu"

slide = prs.slides.add_slide(bullet_slide_layout)
shapes = slide.shapes
title_shape = shapes.title
body_shape = shapes.placeholders[1]
title_shape.text = "Latar Belakang & Tujuan Proyek"
tf = body_shape.text_frame
tf.text = "Transformasi Digital Rukun Tetangga (RT) dan Rukun Warga (RW)."
p = tf.add_paragraph()
p.text = "Meningkatkan transparansi dan kecepatan layanan administrasi."
p.level = 1
p = tf.add_paragraph()
p.text = "Fitur Utama:"
p.level = 0
p = tf.add_paragraph()
p.text = "Manajemen Data Warga (KK & Mutasi)"
p.level = 1
p = tf.add_paragraph()
p.text = "Sistem Iuran Pengelolaan Lingkungan (IPL) & Kas"
p.level = 1
p = tf.add_paragraph()
p.text = "Administrasi Persuratan Terpusat"
p.level = 1
p = tf.add_paragraph()
p.text = "Pemantauan Kesehatan Warga (Posyandu)"
p.level = 1

slide = prs.slides.add_slide(bullet_slide_layout)
shapes = slide.shapes
title_shape = shapes.title
body_shape = shapes.placeholders[1]
title_shape.text = "Aspek Teknologi (Tech Stack)"
tf = body_shape.text_frame
tf.text = "Sistem ini menggunakan arsitektur modern (Decoupled Architecture)."
p = tf.add_paragraph()
p.text = "Backend: Laravel (PHP)"
p.level = 0
p = tf.add_paragraph()
p.text = "API RESTful untuk komunikasi data."
p.level = 1
p = tf.add_paragraph()
p.text = "Manajemen basis data menggunakan MySQL & Eloquent ORM."
p.level = 1
p = tf.add_paragraph()
p.text = "Autentikasi menggunakan Laravel Sanctum (Token-based)."
p.level = 1
p = tf.add_paragraph()
p.text = "Frontend: Next.js (React & TypeScript)"
p.level = 0
p = tf.add_paragraph()
p.text = "Render dinamis (Client-Side) dan navigasi cepat."
p.level = 1
p = tf.add_paragraph()
p.text = "Tailwind CSS untuk antarmuka pengguna yang responsif & estetis."
p.level = 1
p = tf.add_paragraph()
p.text = "Card-Layout untuk kemudahan akses di perangkat mobile (HP)."
p.level = 1

slide = prs.slides.add_slide(bullet_slide_layout)
shapes = slide.shapes
title_shape = shapes.title
body_shape = shapes.placeholders[1]
title_shape.text = "Aktor & Hak Akses (Multi-Role)"
tf = body_shape.text_frame
tf.text = "Sistem mendukung berbagai tingkat hierarki kepengurusan."
p = tf.add_paragraph()
p.text = "Pengurus RW: Ketua RW, Sekretaris RW, Bendahara RW."
p.level = 1
p = tf.add_paragraph()
p.text = "Fokus pada rekapitulasi data gabungan antar RT dan validasi surat akhir."
p.level = 2
p = tf.add_paragraph()
p.text = "Pengurus RT: Ketua RT, Sekretaris RT, Bendahara RT."
p.level = 1
p = tf.add_paragraph()
p.text = "Fokus pada manajemen warga lokal, penarikan IPL, dan verifikasi awal."
p.level = 2
p = tf.add_paragraph()
p.text = "Petugas Lapangan: Satpam (Keamanan) & Kader Posyandu."
p.level = 1
p = tf.add_paragraph()
p.text = "Fokus pada fungsi khusus seperti pencatatan kesehatan & log kunjungan."
p.level = 2
p = tf.add_paragraph()
p.text = "Warga Biasa:"
p.level = 1
p = tf.add_paragraph()
p.text = "Mengajukan surat, melihat riwayat pembayaran, melaporkan perpindahan."
p.level = 2

slide = prs.slides.add_slide(bullet_slide_layout)
shapes = slide.shapes
title_shape = shapes.title
body_shape = shapes.placeholders[1]
title_shape.text = "Alur Bisnis: Kependudukan & Mutasi"
tf = body_shape.text_frame
tf.text = "Pencatatan data keluarga dinamis berbasis Kartu Keluarga (KK)."
p = tf.add_paragraph()
p.text = "Mutasi / Pindah Rumah:"
p.level = 0
p = tf.add_paragraph()
p.text = "Warga mengajukan permohonan pindah secara mandiri melalui dasbor."
p.level = 1
p = tf.add_paragraph()
p.text = "Pilihan pindah: Dalam RT, Lintas RT, atau Keluar Perumahan."
p.level = 1
p = tf.add_paragraph()
p.text = "Sistem mengirimkan 'Alert' kepada Ketua RT."
p.level = 1
p = tf.add_paragraph()
p.text = "Setelah di-Approve oleh Pengurus, data rumah & RT otomatis ter-update."
p.level = 1

slide = prs.slides.add_slide(bullet_slide_layout)
shapes = slide.shapes
title_shape = shapes.title
body_shape = shapes.placeholders[1]
title_shape.text = "Alur Bisnis: Keuangan & Kas"
tf = body_shape.text_frame
tf.text = "Digitalisasi transparansi iuran."
p = tf.add_paragraph()
p.text = "Dompet Warga (Wallet):"
p.level = 0
p = tf.add_paragraph()
p.text = "Warga melakukan Top-Up dan mengunggah bukti transfer."
p.level = 1
p = tf.add_paragraph()
p.text = "Status awal 'Pending'. Bendahara RT menyetujui, lalu saldo bertambah."
p.level = 1
p = tf.add_paragraph()
p.text = "Iuran Pengelolaan Lingkungan (IPL):"
p.level = 0
p = tf.add_paragraph()
p.text = "Tagihan otomatis (Generate Billing) setiap awal bulan oleh Bendahara RT."
p.level = 1
p = tf.add_paragraph()
p.text = "Warga dapat membayar dengan fitur Potong Saldo (Wallet) secara instan."
p.level = 1
p = tf.add_paragraph()
p.text = "Pembagian Persentase Kas: Sebagian kas masuk ke RT, sebagian disetor ke RW."
p.level = 1

slide = prs.slides.add_slide(bullet_slide_layout)
shapes = slide.shapes
title_shape = shapes.title
body_shape = shapes.placeholders[1]
title_shape.text = "Alur Bisnis: Persuratan (Paperless)"
tf = body_shape.text_frame
tf.text = "Menghilangkan birokrasi manual pembuatan Surat Pengantar."
p = tf.add_paragraph()
p.text = "Tahap 1: Warga mengisi form & mengunggah dokumen di aplikasi."
p.level = 1
p = tf.add_paragraph()
p.text = "Tahap 2: Sekretaris RT / Ketua RT memberikan verifikasi digital."
p.level = 1
p = tf.add_paragraph()
p.text = "Tahap 3: Sekretaris RW / Ketua RW menerbitkan persetujuan akhir."
p.level = 1
p = tf.add_paragraph()
p.text = "Tahap 4: Surat cetak dapat dihasilkan dengan status terverifikasi."
p.level = 1

slide = prs.slides.add_slide(bullet_slide_layout)
shapes = slide.shapes
title_shape = shapes.title
body_shape = shapes.placeholders[1]
title_shape.text = "Alur Bisnis: Posyandu & Kesehatan"
tf = body_shape.text_frame
tf.text = "Pencatatan riwayat kesehatan warga rentan."
p = tf.add_paragraph()
p.text = "Balita: Pemantauan tumbuh kembang (Berat & Tinggi Badan)."
p.level = 1
p = tf.add_paragraph()
p.text = "Lansia: Pemantauan tekanan darah (Tensi) secara berkala."
p.level = 1
p = tf.add_paragraph()
p.text = "Responsif Mobile: Tampilan dirancang berbentuk 'Card Layout' untuk kemudahan kader memasukkan data langsung di lapangan melalui Smartphone."
p.level = 1

slide = prs.slides.add_slide(bullet_slide_layout)
shapes = slide.shapes
title_shape = shapes.title
body_shape = shapes.placeholders[1]
title_shape.text = "Kesimpulan & Pencapaian"
tf = body_shape.text_frame
tf.text = "SIP-BTR memodernisasi tata kelola lingkungan dengan:"
p = tf.add_paragraph()
p.text = "Pengalaman Pengguna (UX) yang sangat diperhatikan (Responsif & Estetis)."
p.level = 1
p = tf.add_paragraph()
p.text = "Integritas Data yang kuat antar hierarki RT/RW."
p.level = 1
p = tf.add_paragraph()
p.text = "Otomatisasi Finansial (Potong Saldo IPL, Setoran RW) yang menghilangkan kerumitan pembukuan manual."
p.level = 1
p = tf.add_paragraph()
p.text = "Kesiapan Produksi (Production-Ready) menggunakan arsitektur Laravel & Next.js."
p.level = 1

prs.save("Presentasi_UAS_SIP_BTR.pptx")
print("Presentation generated successfully!")
